* PROJ Rust
** PROJ Programming Patterns
*** PROJ Error Handling
**** ? / Result<>
- Interesting pattern for cumulating results into a Result<X, _>, where X is your desired type and _ is the error. The `anyhow` crate is also interesting
#+BEGIN_SRC
let options = SkimOptionsBuilder::default()
  .multi(false)
  .prompt(Some(prompt))
  .build()
  .map_err(|e| anyhow::anyhow!("Failed to build skim options: {}", e))?;
#+END_SRC
** PROJ FAQ
*** PROJ VsCode FAQ
**** When VsCode does not recognize tests

- To launch and run Rust tests in VS Code, you primarily use the rust-analyzer extension, which provides in-editor controls and integrates with the Test Explorer. 

- Install Rust: Ensure Rust is installed on your system.
- Install rust-analyzer extension: In VS Code, go to the Extensions view (Ctrl+Shift+X or the extensions icon in the Activity Bar), search for "rust-analyzer", and install it.
- Enable Test Explorer (if needed): By default, the Test Explorer should be enabled, but if you don't see tests, check your VS Code settings for rust-analyzer.testExplorer and ensure it is ticked. 

- then find a file, run the tests. They will appear on the "Testing" tab (the lab container icon)

** PROJ Pipeline
*** For caching the dependencies, use this

#+BEGIN_SRC
# Dockerfile
RUN echo "fn main() {}" >> main.rs
RUN cargo build # caches dependencies
COPY main.rs /app
RUN cargo build # caches code
#+END_SRC

** Testing tricks
*** Run all failing crates in a workspace

```makefile
test-rest:
        touch .test-failing .test-failing-tmp
        if [[ $$(wc -l .test-failing | awk '{print $$1}') -eq 0 ]]; then \
                echo "No test-failing/empty found. Adding all"; \
                rm -f .test-failing && touch .test-failing; \
                find crates -maxdepth 1 -type d | cut -d'/' -f2 | grep -v "^\crates" >> .test-failing; \
        fi
        #cat .test-failing
        while IFS= read -r line; do cargo test -p "$$line" || echo "$$line" >> .test-failing-tmp; done < ".test-failing"
        -mv .test-failing-tmp .test-failing
.PHONY: test-rest
```
